### PR TITLE
External Shims

### PR DESCRIPTION
**Pull request by orionshock**
This extends LW by adding in support for common addons that have their tooltip functionality easily accessible.

### CODE REVIEW

**Comment by brykrys** [comment]
Thank you for your proposals

I've looked over the code and while i do like some things, this is not quite how I'd want to do this:

Originally I designed LW to support separate plugin AddOns to do this sort of thing, but that hasn't worked out... So I had been considering bundling or embedding into the main LW package, but I hadn't figured out how I want to do it yet.

Notes:

LibExtraTip is supposed to be covered by https://www.curseforge.com/wow/addons/linkwrangler_auctioneer (although I haven't updated it recently) - I had considered either bundling it or just embedding LibExtraTip itself, but I haven't figured it out yet.

Also (minor thing) LibStub is not bundled in LW, so must check it exists before using

I like to avoid creating extra event frames (if they do nothing after the Load phase) if they can worked around

Your proposed AddOn shims (other than LibExtraTip) are new to me, as I don't use them myself, thank you for that information :) 

I suspect some of your proposed AddOns are applicable to Retail too :)

**Comment by orionshock** [comment]
These are the addons I use and wanted to show in LinkWrangler Tips. There are a few others where their tip handler was inaccessible from the outside and I sent in code updates to account for LW in someway (like with Gargul, had to get them to expose their tip handler so LW can get to it from the outside).

As for event frames, I cannot help you there, sometimes you have to use a throw away frame an there is no other solution.

As for use in Retail, no idea, don't play retail.

**Comment by brykrys** [comment]
I've implemented a Plugins subfolder for LinkWrangler, and a method of piggybacking on LW's event handler (via a new RegisterCallback option).

I am also working on implementing the LibextraTip plugin - after all it is one of my AddOns :)

**Comment by brykrys** [comment]
Hi, are you planning to resubmit this with the Plugins changes?

**Pull request closed without merging**
